# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

demo_chatty1 <- function() {
    invisible(.Call('_classExamples_demo_chatty1', PACKAGE = 'classExamples'))
}

demo_chatty2 <- function(n) {
    invisible(.Call('_classExamples_demo_chatty2', PACKAGE = 'classExamples', n))
}

demo_chatty3 <- function(n) {
    invisible(.Call('_classExamples_demo_chatty3', PACKAGE = 'classExamples', n))
}

demo_chatty4 <- function(n, reserve = TRUE) {
    invisible(.Call('_classExamples_demo_chatty4', PACKAGE = 'classExamples', n, reserve))
}

demo_chatty5 <- function(n, reserve = TRUE) {
    invisible(.Call('_classExamples_demo_chatty5', PACKAGE = 'classExamples', n, reserve))
}

demo_chatty6 <- function(n, reserve = TRUE) {
    invisible(.Call('_classExamples_demo_chatty6', PACKAGE = 'classExamples', n, reserve))
}

demo_chatty7 <- function(n) {
    invisible(.Call('_classExamples_demo_chatty7', PACKAGE = 'classExamples', n))
}

demo_derivation_1 <- function(x) {
    .Call('_classExamples_demo_derivation_1', PACKAGE = 'classExamples', x)
}

demo_derivation_2 <- function(x) {
    .Call('_classExamples_demo_derivation_2', PACKAGE = 'classExamples', x)
}

